// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuhTjhdrNQFt1DWCraT_SwfDiKz1cdvUk',
    appId: '1:283099463283:web:91dc16f309e686d61d3406',
    messagingSenderId: '283099463283',
    projectId: 'verify-otp-f794a',
    authDomain: 'verify-otp-f794a.firebaseapp.com',
    storageBucket: 'verify-otp-f794a.firebasestorage.app',
    measurementId: 'G-4JKXPZQSXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4gEH4-xu7bqhovhSxngP6C1SN2AImLpE',
    appId: '1:283099463283:android:a47dfc572306f86b1d3406',
    messagingSenderId: '283099463283',
    projectId: 'verify-otp-f794a',
    storageBucket: 'verify-otp-f794a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrtoLcI-MsSR0palWWpgQSYo8lvnDCR2Y',
    appId: '1:283099463283:ios:99062550424cd06a1d3406',
    messagingSenderId: '283099463283',
    projectId: 'verify-otp-f794a',
    storageBucket: 'verify-otp-f794a.firebasestorage.app',
    iosBundleId: 'com.example.umcCareClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrtoLcI-MsSR0palWWpgQSYo8lvnDCR2Y',
    appId: '1:283099463283:ios:99062550424cd06a1d3406',
    messagingSenderId: '283099463283',
    projectId: 'verify-otp-f794a',
    storageBucket: 'verify-otp-f794a.firebasestorage.app',
    iosBundleId: 'com.example.umcCareClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuhTjhdrNQFt1DWCraT_SwfDiKz1cdvUk',
    appId: '1:283099463283:web:9f0d0f4722f7fc7a1d3406',
    messagingSenderId: '283099463283',
    projectId: 'verify-otp-f794a',
    authDomain: 'verify-otp-f794a.firebaseapp.com',
    storageBucket: 'verify-otp-f794a.firebasestorage.app',
    measurementId: 'G-GY9TZJ329W',
  );
}
